site_name: LearnD3D11
site_author: deccer
site_url: https://graphicsprogramming.github.io/learnd3d11
repo_name: graphicsprogramming/learnd3d11
repo_url: https://github.com/graphicsprogramming/learnd3d11
site_description: Learn D3D11
copyright: Copyright 2022 Graphics Programming
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    code: Roboto Mono
  language: en
  features:
    - tabs
    - instant
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/graphicsprogramming/learnd3d11
      name: Graphics Programming on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6mgNGk7
      name: Graphics Programming on discord
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - markdown.extensions.toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
nav:
  - Introduction: index.md
  - 'Getting Started':
      - 'D3D11': '1-getting-started/d3d11.md'
      - 'Creating a Window': '1-getting-started/creating-a-window.md'
      - 'Hello Window': '1-getting-started/hello-window.md'
      - 'Hello Frog': '1-getting-started/hello-frog.md'
      - 'Shaders': '1-getting-started/shaders.md'
      - 'Textures': '1-getting-started/textures.md'
      - 'Transformations': '1-getting-started/transformations.md'
      - 'Coordinate Systems': '1-getting-started/coordinate-systems.md'
      - 'Camera': '1-getting-started/camera.md'
      - 'Review': '1-getting-started/review.md'
  - 'Lighting':
      - 'Color': '2-lighting/colors.md'
      - 'Basic Lighting': '2-lighting/basic-lighting.md'
      - 'Materials': '2-lighting/materials.md'
      - 'Lighting Maps': '2-lighting/lighting-maps.md'
      - 'Light Casters': '2-lighting/light-casters.md'
      - 'Multiple Lights': '2-lighting/multiple-lights.md'
      - 'Review': '2-lighting/review.md'
  - 'Model Loading':
      - 'Assimp': '3-model-loading/assimp.md'
      - 'Mesh': '3-model-loading/mesh.md'
      - 'Model': '3-model-loading/model.md'
  - 'Advanced D3D11':
      - 'Depth Testing': '4-advanced-d3d11/depth-testing.md'
      - 'Stencil Testing': '4-advanced-d3d11/stencil-testing.md'
      - 'Blending': '4-advanced-d3d11/blending.md'
      - 'Face Culling': '4-advanced-d3d11/face-culling.md'
      - 'Render Targets': '4-advanced-d3d11/rendertargets.md'
      - 'Cube Maps': '4-advanced-d3d11/cube-maps.md'
      - 'Advanced Data': '4-advanced-d3d11/advanced-data.md'
      - 'Advanced HLSL': '4-advanced-d3d11/advanced-hlsl.md'
      - 'Geometry Shader': '4-advanced-d3d11/geometry-shader.md'
      - 'Instancing': '4-advanced-d3d11/instancing.md'
      - 'Anti Aliasing': '4-advanced-d3d11/antialiasing.md'
      - 'OIT':
          - 'Introduction': '4-advanced-d3d11/oit/introduction.md'
          - 'Weighted Blended': '4-advanced-d3d11/oit/weighted-blended.md'
      - 'Skeletal Animation': '4-advanced-d3d11/skeletal-animation.md'
      - 'Tessellation': '4-advanced-d3d11/tessellation.md'
      - 'Scene Graph':
           - 'Introduction': '4-advanced-d3d11/scene-graph/scene-graph.md'
           - 'Frustum Culling': '4-advanced-d3d11/scene-graph/frustum-culling.md'
  - 'Advanced Lighting':
      - 'Advanced Lighting': '5-advanced-lighting/advanced-lighting.md'
      - 'Gamma Correction': '5-advanced-lighting/gamma-correction.md'
      - 'Shadows':
          - 'Shadow Mapping': '5-advanced-lighting/shadows/shadow-mapping.md'
          - 'Point Shadows': '5-advanced-lighting/shadows/point-shadows.md'
          - 'CSM': '5-advanced-lighting/shadows/cascade-shadow-mapping.md'
      - 'Normal Mapping': '5-advanced-lighting/normal-mapping.md'
      - 'Parallax Mapping': '5-advanced-lighting/parallax-mapping.md'
      - 'HDR': '5-advanced-lighting/hdr.md'
      - 'Bloom': '5-advanced-lighting/bloom.md'
      - 'Deferred Shading': '5-advanced-lighting/deferred-shading.md'
      - 'SSAO': '5-advanced-lighting/ssao.md'
  - 'PBR':
      - 'Theory': '6-pbr/theory.md'
      - 'Lighting': '6-pbr/lighting.md'
      - 'IBL': '6-pbr/ibl.md'
  - 'In Practice':
      - 'Debugging': '7-in-practice/debugging.md'
      - 'Text Rendering': '7-in-practice/text-rendering.md'
      - '2D Game': '7-in-practice/2d-game.md'
  - 'Code Repository': '8-code/repository.md'
  - About: about.md