site_name: LearnD3D11
site_author: deccer
site_url: https://graphicsprogramming.github.io/learnd3d11
repo_name: graphicsprogramming/learnd3d11
repo_url: https://github.com/graphicsprogramming/learnd3d11
site_description: Learn D3D11
copyright: Copyright 2022 Graphics Programming
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    code: Roboto Mono
  language: en
  features:
    - tabs
    - instant
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/graphicsprogramming/learnd3d11
      name: Graphics Programming on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6mgNGk7
      name: Graphics Programming on discord
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - markdown.extensions.toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
nav:
  - Introduction: index.md
  - 'Getting Started':
      - 'D3D11': 'getting-started/d3d11.md'
      - 'Creating a Window': 'getting-started/creating-a-window.md'
      - 'Hello Window': 'getting-started/hello-window.md'
      - 'Hello Frog': 'getting-started/hello-frog.md'
      - 'Shaders': 'getting-started/shaders.md'
      - 'Textures': 'getting-started/textures.md'
      - 'Transformations': 'getting-started/transformations.md'
      - 'Coordinate Systems': 'getting-started/coordinate-systems.md'
      - 'Camera': 'getting-started/camera.md'
      - 'Review': 'getting-started/review.md'
  - 'Lighting':
      - 'Color': 'lighting/colors.md'
      - 'Basic Lighting': 'lighting/basic-lighting.md'
      - 'Materials': 'lighting/materials.md'
      - 'Lighting Maps': 'lighting/lighting-maps.md'
      - 'Light Casters': 'lighting/light-casters.md'
      - 'Multiple Lights': 'lighting/multiple-lights.md'
      - 'Review': 'lighting/review.md'
  - 'Model Loading':
      - 'Assimp': 'model-loading/assimp.md'
      - 'Mesh': 'model-loading/mesh.md'
      - 'Model': 'model-loading/model.md'
  - 'Advanced D3D11':
      - 'Depth Testing': 'advanced-d3d11/depth-testing.md'
      - 'Stencil Testing': 'advanced-d3d11/stencil-testing.md'
      - 'Blending': 'advanced-d3d11/blending.md'
      - 'Face Culling': 'advanced-d3d11/face-culling.md'
      - 'Render Targets': 'advanced-d3d11/rendertargets.md'
      - 'Cube Maps': 'advanced-d3d11/cube-maps.md'
      - 'Advanced Data': 'advanced-d3d11/advanced-data.md'
      - 'Advanced HLSL': 'advanced-d3d11/advanced-hlsl.md'
      - 'Geometry Shader': 'advanced-d3d11/geometry-shader.md'
      - 'Instancing': 'advanced-d3d11/instancing.md'
      - 'Anti Aliasing': 'advanced-d3d11/antialiasing.md'
      - 'OIT':
          - 'Introduction': 'advanced-d3d11/oit/introduction.md'
          - 'Weighted Blended': 'advanced-d3d11/oit/weighted-blended.md'
      - 'Skeletal Animation': 'advanced-d3d11/skeletal-animation.md'
      - 'CSM': 'advanced-d3d11/cascade-shadow-mapping.md'
      - 'Tessellation': 'advanced-d3d11/tessellation.md'
      - 'Scene Graph':
           - 'Introduction': 'advanced-d3d11/scene-graph/scene-graph.md'
           - 'Frustum Culling': 'advanced-d3d11/scene-graph/frustum-culling.md'
  - 'Advanced Lighting':
      - 'Advanced Lighting': 'advanced-lighting/advanced-lighting.md'
      - 'Gamma Correction': 'advanced-lighting/gamma-correction.md'
      - 'Shadows':
          - 'Shadow Mapping': 'advanced-lighting/shadows/shadow-mapping.md'
          - 'Point Shadows': 'advanced-lighting/shadows/point-shadows.md'
      - 'Normal Mapping': 'advanced-lighting/normal-mapping.md'
      - 'Parallax Mapping': 'advanced-lighting/parallax-mapping.md'
      - 'HDR': 'advanced-lighting/hdr.md'
      - 'Bloom': 'advanced-lighting/bloom.md'
      - 'Deferred Shading': 'advanced-lighting/deferred-shading.md'
      - 'SSAO': 'advanced-lighting/ssao.md'
  - 'PBR':
      - 'Theory': 'pbr/theory.md'
      - 'Lighting': 'pbr/lighting.md'
      - 'IBL': 'pbr/ibl.md'
  - 'In Practice':
      - 'Debugging': 'in-practice/debugging.md'
      - 'Text Rendering': 'in-practice/text-rendering.md'
      - '2D Game': 'in-practice/2d-game.md'
  - 'Code Repository': 'code-repository.md'
  - About: about.md